version: "3"
services:
  postgres-multimodal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PG_VERSION=12
        - TIMESCALE_VERSION=2.11
        - APACHE_AGE_VERSION=1.3.0

    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./migrations/:/migrations/
    networks:
      - postgres-multimodal
    ports:
      - "5434:5432"
  liquibase:
    image: liquibase/liquibase
    command: --hub-mode=off --headless=true --changeLogFile=changelog/root.changelog.xml --url=jdbc:postgresql://postgres-multimodal:5432/postgres --username=postgres --password=password update
    volumes:
      - ./migrations/:/liquibase/changelog
    depends_on:
      - postgres-multimodal
    links:
      - postgres-multimodal
    networks:
      - postgres-multimodal
    restart: on-failure

networks:
  postgres-multimodal:
